### PR TITLE
Update psr/log dependency

### PR DESCRIPTION
**Pull request by jochensengier**

### CODE REVIEW

**Comment by kouinkouin** [comment]
https://getcomposer.org/doc/articles/versions.md#caret-version-range-

`^1.0` includes `^1.1`. Am I wrong?

Then, commit the file `composer.lock`

**Comment by jochensengier** [comment]
No, you're not wrong. _Mea culpa!_

However, when I try to install the library in a project where psr/log 1.1.0 is required, I get the following error:

`antidot-be/bpost-api-library 3.4.0 requires psr/log ~1.0.0 -> satisfiable by psr/log[1.0.0, 1.0.1, 1.0.2].
`
```
composer require antidot-be/bpost-api-library
Using version ^3.4 for antidot-be/bpost-api-library
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install antidot-be/bpost-api-library 3.4.7
    - Conclusion: don't install antidot-be/bpost-api-library 3.4.6
    - Conclusion: don't install antidot-be/bpost-api-library 3.4.5
    - Conclusion: don't install antidot-be/bpost-api-library 3.4.3
    - Conclusion: remove psr/log 1.1.0
    - Installation request for antidot-be/bpost-api-library ^3.4 -> satisfiable by antidot-be/bpost-api-library[3.4.0, 3.4.3, 3.4.5, 3.4.6, 3.4.7].
    - Conclusion: don't install psr/log 1.1.0
    - antidot-be/bpost-api-library 3.4.0 requires psr/log ~1.0.0 -> satisfiable by psr/log[1.0.0, 1.0.1, 1.0.2].
    - Can only install one of: psr/log[1.0.0, 1.1.0].
    - Can only install one of: psr/log[1.0.1, 1.1.0].
    - Can only install one of: psr/log[1.0.2, 1.1.0].
    - Installation request for psr/log (locked at 1.1.0) -> satisfiable by psr/log[1.1.0].
```

**Comment by kouinkouin** [comment]
I will try to make a `composer install` with the updated code (with changes of #22) on the day

**Comment by jochensengier** [comment]
Sorry for wasting your time, I forgot to try the master branch...
Works like a charm!

```{
"require": {
        "antidot-be/bpost-api-library": "dev-master",
},
"repositories": [
      {
            "type": "vcs",
            "url": "https://github.com/Antidot-be/bpost-api-library"
        }
    ]
}
```

**Comment by kouinkouin** [comment]
Nice :-) .

I will make a release [I don't know when] in the week, run a `composer update` the next Monday to be sure.

**Comment by jochensengier** [comment]
Awesome, thanks!!!

**Comment by kouinkouin** [comment]
https://packagist.org/packages/antidot-be/bpost-api-library#3.4.8

**Pull request closed without merging**
