### PR TITLE
Fix logging package constraint

### PR DESCRIPTION
**Pull request by michielkalle**
New pull request, see https://github.com/Antidot-be/bpost-api-library/pull/21, created from new master

### CODE REVIEW

**Comment by kouinkouin** [comment]
thanks :)

**Comment by michielkalle** [comment]
Will there be a hotfix release?

**Comment by kouinkouin** [comment]
> Will there be a hotfix release?

Indeed, I will do it in the week :-)

**Comment by kouinkouin** [comment]
https://packagist.org/packages/antidot-be/bpost-api-library#3.4.8

**Pull request merged**
